passmenu

diff --git a/.config/scripts/dmenu/dm-pass b/.config/scripts/dmenu/dm-pass
--- a/.config/scripts/dmenu/dm-pass
+++ b/.config/scripts/dmenu/dm-pass
@@ -1,14 +1,40 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 DMENU_OPTIONS=`dwm -m`
-ITEMS="$(pass show | sed 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g')"
 
-OPTIONS=""
-while IFS= read -r LINE; do
-    read -ra TOKENS <<< $LINE
-    OPTIONS="$OPTIONS${TOKENS[@]:1}\n"
-done <<< ${ITEMS[@]:1}
+shopt -s nullglob globstar
 
-CHOICE=$(printf "$OPTIONS" | dmenu $DMENU_OPTIONS -i -p "")
+typeit=0
+if [[ $1 == "--type" ]]; then
+	typeit=1
+	shift
+fi
 
-pass -c "$CHOICE"
+if [[ -n $WAYLAND_DISPLAY ]]; then
+	dmenu=dmenu-wl
+	xdotool="ydotool type --file -"
+elif [[ -n $DISPLAY ]]; then
+	dmenu=dmenu
+	
+	xdotool="xdotool type --clearmodifiers --file -"
+else
+	echo "Error: No Wayland or X11 display detected" >&2
+	exit 1
+fi
+
+prefix=${PASSWORD_STORE_DIR-~/.password-store}
+password_files=( "$prefix"/**/*.gpg )
+password_files=( "${password_files[@]#"$prefix"/}" )
+password_files=( "${password_files[@]%.gpg}" )
+
+
+password=$(printf '%s\n' "${password_files[@]}" | dmenu $DMENU_OPTIONS "$@")
+
+
+[[ -n $password ]] || exit
+
+if [[ $typeit -eq 0 ]]; then
+	pass show -c "$password" 2>/dev/null
+else
+	pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } | $xdotool
+fi
